FROM alpine
LABEL vendor=DHUniWien

RUN apk update \
 && apk upgrade \
 && apk add --no-cache \
    gcc \
    make \
    wget \
    perl \
    perl-dev

RUN pwd && ls -l

RUN wget --no-check-certificate https://cpanmin.us -O cpanm && \
    perl cpanm App::cpanminus

RUN cpanm \
    Devel::OverloadInfo \
    Text::Tradition \
    Module::Install::Catalyst

# stemmaweb dependencies
#
RUN find && pwd
COPY sources/ /tmp/
RUN /usr/local/bin/cpanm --installdeps /tmp/sources/
# RUN /usr/local/bin/cpanm --installdeps ./sources/

# timezone Europe/Vienna
RUN cp /usr/share/zoneinfo/Europe/Vienna /etc/localtime && \
    echo "Europe/Vienna" > /etc/timezone && \
    apk del tzdata
