---
resources:
    - name: ci
      type: git
      source:
        uri: {{ci-uri}}
        paths:
          - pipelines/stemmaweb/resources

    ## stemmaREST
    ##
    - name: stemmarest-sources
      type: git
      source:
        uri: {{stemmarest-sources-uri}}
        paths: [stemmarest, ci/resources]

    - name: stemmarest-test-image
      type: docker-image
      source:
        repository: {{stemmarest-test-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: stemmarest-test-version
      type: semver
      source:
        driver: git
        uri: {{version-uri}}
        branch: master
        file: {{stemmarest-test-version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

    - name: stemmarest-final-base-image
      type: docker-image
      source:
        repository: {{stemmarest-final-base-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: stemmarest-final-base-version
      type: semver
      source:
        driver: git
        uri: {{version-uri}}
        branch: master
        file: {{stemmarest-final-base-version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

    ## moe
    ##
    - name: moe-sources
      type: git
      source:
        uri: {{moe-sources-uri}}
        paths: [moe, ci/resources]
        private_key: {{DHUniWienMU-priv-key}}

    - name: moe-ci-image
      type: docker-image
      source:
        repository: {{moe-ci-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: moe-ci-version
      type: semver
      source:
        driver: git
        uri: {{moe-version-uri}}
        branch: master
        file: {{moe-version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

    ## tools
    ##
    - name: tools-sources-dockerfiles
      type: git
      source:
        uri: {{tools-sources-dockerfiles-uri}}
        paths: [ci/resources]

    - name: tools-ci-image
      type: docker-image
      source:
        repository: {{tools-ci-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: tools-ci-version
      type: semver
      source:
        driver: git
        uri: {{tools-ci-image-version-uri}}
        branch: master
        file: {{tools-ci-image-version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

    - name: tools-final-base-version
      type: semver
      source:
        driver: git
        uri: {{tools-final-base-image-version-uri}}
        branch: master
        file: {{tools-final-base-image-version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

    - name: tools-final-base-image
      type: docker-image
      source:
        repository: {{tools-final-base-image}}
        insecure_registries: [ {{insecure-registries}} ]

    ## collatex-ci
    ##
    - name: collatex-sources
      type: git
      source:
        uri: {{collatex-sources-uri}}
        paths: [collatex-core, collatex-tools, ci/resources]
        # private_key: {{DHUniWienMU-priv-key}}

    - name: collatex-ci-image
      type: docker-image
      source:
        repository: {{collatex-ci-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: collatex-version
      type: semver
      source:
        driver: git
        uri: {{collatex-image-version-uri}}
        branch: master
        file: {{collatex-image-version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

    ## stemmaWEB
    ##
    - name: stemmaweb-final-base-image
      type: docker-image
      source:
        repository: {{stemmaweb-final-base-image}}
        insecure_registries: [ {{insecure-registries}} ]

    - name: stemmaweb-final-base-image-version
      type: semver
      source:
        driver: git
        uri: {{stemmaweb-final-base-image-version-uri}}
        branch: master
        file: {{stemmaweb-final-base-image-version-file}}
        initial_version: "0.0.0"
        private_key: {{DHUniWienMU-priv-key}}

jobs:
    - name: build-stemmarest-test-image

      plan:
        - aggregate:
          - get: stemmarest-sources
            trigger: true
          - get: stemmarest-test-version
          - get: stemmarest-final-base-version

        - put: stemmarest-test-version
          params:
            bump: patch

        - put: stemmarest-test-image
          params:
            build: stemmarest-sources/ci/
            dockerfile: stemmarest-sources/ci/resources/Dockerfile-stemmarest-ci-test
            tag: stemmarest-test-version/version
            tag_as_latest: True


    - name: build-stemmarest-final-base-image

      plan:
        - aggregate:
          - get: stemmarest-sources
            trigger: true
          - get: stemmarest-test-version
          - get: stemmarest-final-base-version

        - put: stemmarest-final-base-version
          params:
            bump: patch

        - put: stemmarest-final-base-image
          params:
            build: stemmarest-sources/ci/
            dockerfile: stemmarest-sources/ci/resources/Dockerfile-stemmarest-final-base
            tag: stemmarest-final-base-version/version
            tag_as_latest: True


    ## moe
    ##
    - name: build-moe-ci-image

      plan:
        - aggregate:
          - get: moe-sources
            trigger: true
          - get: moe-ci-version

        - put: moe-ci-version
          params:
            bump: patch

        - put: moe-ci-image
          params:
            build: moe-sources/ci/
            dockerfile: moe-sources/ci/resources/Dockerfile-ci
            tag: moe-ci-version/version
            tag_as_latest: True


    ## tools
    ##
    - name: build-tools-ci-image

      plan:
        - aggregate:
          - get: tools-sources-dockerfiles
            trigger: true
          - get: tools-ci-version

        - put: tools-ci-version
          params:
            bump: patch

        - put: tools-ci-image
          params:
            build: tools-sources-dockerfiles/ci/
            dockerfile: {{tools-ci-image-df}}
            tag: tools-ci-version/version
            tag_as_latest: True


    - name: build-tools-final-base-image

      plan:
        - aggregate:
          - get: tools-sources-dockerfiles
            trigger: true
          - get: tools-final-base-version

        - put: tools-final-base-version
          params:
            bump: patch

        - put: tools-final-base-image
          params:
            build: tools-sources-dockerfiles/ci/
            dockerfile: {{tools-final-base-image-df}}
            tag: tools-final-base-version/version
            tag_as_latest: True


    - name: build-collatex-ci-image

      plan:
        - aggregate:
          - get: collatex-sources
            trigger: true
          - get: collatex-version

        - put: collatex-version
          params:
            bump: patch

        - put: collatex-ci-image
          params:
            build: collatex-sources/ci/
            dockerfile: collatex-sources/ci/resources/Dockerfile-ci
            tag: collatex-version/version
            tag_as_latest: True
